In [4]:
from scipy.special import softmax
import numpy as np
from matplotlib import pyplot as plt

In [5]:
sim_score = np.array([0.5,0.4,0.1])

In [6]:
y0 = softmax(sim_score)
print(y0)

[0.38832577 0.35137169 0.26030255]


In [7]:
tau = 0.007

## tau controls the how the nedgative samples are penalized; If tau is a very small number, then the negative samples are penalized heavlily; if tau is a very big number, then the distribution is uniform.

In [8]:
y1 = softmax(sim_score/tau)
print(y1)

[9.99999375e-01 6.24874560e-07 1.52465714e-25]


In [11]:
tau = 7000

In [12]:
y2 = softmax(sim_score/tau)
print(y2)

[0.33334127 0.33333651 0.33332222]
